{
    'name': 'TechbotErp Sports Management System ',
    'version': '15.0.1.0.4',
    'summary': 'A module for Manage Complete Sports Activities  ',
    'description': 'Sports  Management System Enterprise version15',
    'category': 'Tools',
    'author': 'TecbotERp',
    'website': "https://techboterp.com",
    'company': 'TechbotErp',
    'license': 'LGPL-3',
    'complexity': 'easy',
    'sequence': '-100',
    'images': [],
    # 'static/description/EMS.jpg'
    'depends': ['base', 'stock', 'hr', 'account', 'crm', 'sale_management', 'account_accountant'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/attendance_marking_wiz.xml',
        'views/crm_lead_views.xml',
        'views/employee_views.xml',
        'views/product_views.xml',
        'views/sale_order_views.xml',
        'views/employee_session_view.xml',
        'views/student_details_view.xml',
        'views/res_partner_view.xml',
        'views/techboterp_menu_views.xml',
    ],
    # 'demo': ['demo/school_demo.xml'],
    'images': ['static/description/banner.png'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
